<?php

namespace STEBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipRepository extends EntityRepository
{
}
